### ISSUE TITLE
[Bug] ToDo 리스트 엔터키로 추가할 경우 2개씩 들어감

### ISSUE THREAD

**Issue by ghk0409** [ghk0409/CTD#28]
- [ + ] 버튼으로 넣으면 정상적으로 1개 들어감
- 엔터키로 추가하면 2개가 추가되는데, 하나는 입력한 정상 내용, 다른 하나는 빈 칸으로 보여짐
- DB에는 똑같은 내용으로 데이터가 2개 저장됨

**Comment by ghk0409** [comment]
추가로 화면 이동이나 새로고침 전까지는 빈 칸으로 유지되는데 여기서 체크박스 체크하면 해당 todo의 id 값이 없어서 /:todoId API 정상 동작 안 됨

**Comment by gyahury** [comment]
이슈 확인 중

**Comment by gyahury** [comment]
1번 이슈는 맥 os 크롬 브라우저 특정 버전에서 발생하는 버그임을 확인 후 조치 중

**Comment by gyahury** [comment]
조치 과정 
1. @keydown.enter.prevent -> @keydown.enter.prevent.once로 변경  
-> 해당 수정은 해결은 되었으나 엔터가 한번 이상 작동을 하지 않기 때문에 근원적인 해결이 아님
2. lodash 라이브러리 적용 
-> lodash 라이브러리의 연속 작동을 막는 debounce를 사용해 한번만 발생시키도록 debouncedSendTodo 메소드를 추가, 적용
-> 정상 작동함을 확인
