### ISSUE TITLE
Nuxt.js 브라우저 창 크기와 상관없이 레이아웃 너비 고정

### ISSUE THREAD

**Issue by gyahury** [ghk0409/CTD#3]
### 이슈
Nuxt.js 프레임워크를 사용하는 프로젝트에서 브라우저 창 크기와 상관없이 레이아웃 너비를 1200px로 고정하려고 함(1200px 이전에는 반응형으로). 여러 가지 방법을 시도했지만, 창 크기를 조절할 때 레이아웃 너비가 여전히 변화함

### 논의사항
Nuxt.js 프로젝트에서 브라우저 창 크기와 상관없이 레이아웃 너비를 고정하는 올바른 방법은 무엇인지

**Comment by gyahury** [comment]
index.vue 의 기존 형식을 지우니 해결되었음. 기존 index.vue 템플릿 소스 자체가 vuetify에 따라 반응형으로 작동하는 것이라 일반 태그로 변경 후 정상 고정을 확인함

**Comment by ghk0409** [comment]
확인
